load("@rules_proto//proto:defs.bzl", "proto_library")
load("@rules_rust_prost//:defs.bzl", "rust_prost_library")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "chat_proto",
    srcs = ["chat.proto"],
)

rust_prost_library(
    name = "chat_rs",
    proto = ":chat_proto",
)
