import * as net from 'net';
import * as os from 'os';
import * as path from 'path';
import * as fs from 'fs';
import { spawn, ChildProcess } from 'child_process';

export interface ServerHandle {
    port: number;
    baseDir: string;
    stop: () => Promise<void>;
}

/** Find a free TCP port on localhost. */
function freePort(): Promise<number> {
    return new Promise((resolve, reject) => {
        const srv = net.createServer();
        srv.listen(0, '127.0.0.1', () => {
            const addr = srv.address() as net.AddressInfo;
            srv.close((err) => (err ? reject(err) : resolve(addr.port)));
        });
    });
}

/** Poll until TCP connect succeeds or timeout expires. */
function waitForPort(port: number, timeoutMs = 15_000): Promise<void> {
    const deadline = Date.now() + timeoutMs;
    return new Promise((resolve, reject) => {
        const attempt = () => {
            if (Date.now() > deadline) {
                return reject(new Error(`Server on port ${port} did not become ready within ${timeoutMs}ms`));
            }
            const sock = net.connect(port, '127.0.0.1');
            sock.on('connect', () => {
                sock.destroy();
                resolve();
            });
            sock.on('error', () => {
                sock.destroy();
                setTimeout(attempt, 150);
            });
        };
        attempt();
    });
}

/**
 * Build the server with `bazel build //server:server`, then spawn it.
 *
 * Why bazel, not cargo:
 *   - The binary is compiled with `option_env!("BAZEL_STATIC") = Some("server")`,
 *     which changes how the server resolves static files and templates.
 *     A plain `cargo build` produces a binary where BAZEL_STATIC is None —
 *     it would look for `static/` instead of `assets/` and fail to find
 *     Tera templates for the Puppeteer tests.
 *   - The `//contracts/chat:chat_rs` prost crate is generated by Bazel;
 *     `cargo build` cannot satisfy that dependency without the generated
 *     source being checked in.
 *
 * DB isolation:
 *   The server always writes its database to `{BASE_PATH}/server/db/main.db`.
 *   We create a temp `BASE_PATH` dir and symlink the read-only `templates/`
 *   and `assets/` trees from the Bazel runfiles into it, while providing a
 *   fresh writable `server/db/` directory.  This gives full isolation between
 *   test runs without duplicating large asset files.
 *
 * `workspaceRoot` defaults to the repo root (two levels up from this file).
 */
export async function startServer(workspaceRoot?: string): Promise<ServerHandle> {
    const root = workspaceRoot ?? path.resolve(__dirname, '..', '..', '..');

    // ── 1. Build ────────────────────────────────────────────────────────────
    await new Promise<void>((resolve, reject) => {
        const build = spawn('bazel', ['build', '//server:server'], {
            cwd: root,
            stdio: ['ignore', 'pipe', 'pipe'],
        });
        build.stderr?.on('data', () => {/* suppress */});
        build.on('close', (code) => {
            if (code === 0) resolve();
            else reject(new Error(`bazel build //server:server exited with code ${code}`));
        });
    });

    // ── 2. Locate runfiles ──────────────────────────────────────────────────
    // `bazel-bin/server/server.runfiles/_main/` is the root used when the
    // binary is run via `bazel run`.  Templates are at `server/templates/`
    // and static assets at `assets/` relative to that root.
    const runfilesMain = path.join(root, 'bazel-bin', 'server', 'server.runfiles', '_main');
    const runfilesTemplates = path.join(runfilesMain, 'server', 'templates');
    const runfilesAssets = path.join(runfilesMain, 'assets');

    // ── 3. Create isolated BASE_PATH ────────────────────────────────────────
    const baseDir = fs.mkdtempSync(path.join(os.tmpdir(), 'e2e_server_'));
    // Symlink read-only trees from runfiles
    fs.symlinkSync(runfilesTemplates, path.join(baseDir, 'server', 'templates'));
    fs.symlinkSync(runfilesAssets, path.join(baseDir, 'assets'));
    // Create a fresh, writable db directory
    fs.mkdirSync(path.join(baseDir, 'server', 'db'), { recursive: true });

    // ── 4. Spawn ─────────────────────────────────────────────────────────────
    const port = await freePort();
    const serverBin = path.join(root, 'bazel-bin', 'server', 'server');

    const proc: ChildProcess = spawn(serverBin, [], {
        cwd: baseDir,
        env: {
            ...process.env,
            HOST: '127.0.0.1',
            PORT: String(port),
            BASE_PATH: baseDir,
            RUST_LOG: 'warn',
        },
        stdio: ['ignore', 'pipe', 'pipe'],
    });

    proc.on('error', (err) => {
        throw new Error(`Failed to spawn server: ${err.message}`);
    });

    await waitForPort(port);

    // ── 5. Teardown ───────────────────────────────────────────────────────────
    const stop = (): Promise<void> =>
        new Promise((resolve) => {
            if (proc.exitCode !== null) {
                fs.rmSync(baseDir, { recursive: true, force: true });
                return resolve();
            }
            proc.once('exit', () => {
                fs.rmSync(baseDir, { recursive: true, force: true });
                resolve();
            });
            proc.kill('SIGTERM');
        });

    return { port, baseDir, stop };
}
