---
- hosts: web
  name: push image 
  vars:
    install_dirr: '/opt/month'
    app_name: 'my_app'
    image_name: 'what_amonth'
  tasks:
  - name: Configure docker daemon log rotation
    ansible.builtin.copy:
      dest: /etc/docker/daemon.json
      mode: "0644"
      content: |
        {
          "log-driver": "json-file",
          "log-opts": {
            "max-size": "10m",
            "max-file": "5"
          }
        }
  - name: Restart docker daemon
    ansible.builtin.systemd:
      name: docker
      state: restarted
  - name: directory exist
    ansible.builtin.file:
      path: "{{ install_dirr }}"
      state: directory
  - name: push image
    ansible.posix.synchronize:
      src: './../image.tar'
      dest: '{{ install_dirr }}'
  - name: Stop docker container
    ansible.builtin.shell: |
      docker stop {{ app_name }} || true
  - name: Remove old container
    ansible.builtin.shell: |
      docker rm {{ app_name }} || true
  - name: Remove old image
    ansible.builtin.shell: docker rmi {{ image_name }} || true
  - name: Load image to docker
    ansible.builtin.shell: docker load --input image.tar
    args:
      chdir: "{{ install_dirr }}"
  - name: run app from docker
    ansible.builtin.shell: |
      docker run \
      --publish 8080:8080 \
      -d \
      --mount source=edk,target=/usr/local/bin/db  \
      --name {{ app_name }} \
      --restart unless-stopped \
      {{ image_name }}
